// <auto-generated />
using libreria_MCLG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace libreria_MCLG.Migrations
{
    [DbContext(typeof(AppDbContext)), Migration("20231101171407_InitialDataBaseMigration")]
    internal class InitialDataBaseMigrationBase : InitialDataBaseMigrationBaseBase
    {
    }
}